DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS aufgabe;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  passcode TEXT NOT NULL
);

CREATE TABLE aufgabe (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER FOREIGN KEY REFERENCES user(id),
  titel TEXT NOT NULL,
  beginn DATE NOT NULL,
  enddatum DATE NOT NULL,
  fortschritt INT NOT NULL,
  prioritaet TEXT NOT NULL
);